// <auto-generated />
using System;
using FoodOrder.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FoodOrder.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FoodOrder.Domain.Entities.Address", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);
                b.Property<string>("Apartment").HasMaxLength(20).HasColumnType("character varying(20)");
                b.Property<string>("Comment").HasMaxLength(500).HasColumnType("character varying(500)");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasDefaultValueSql("now()");
                b.Property<string>("Entrance").HasMaxLength(10).HasColumnType("character varying(10)");
                b.Property<string>("Floor").HasMaxLength(10).HasColumnType("character varying(10)");
                b.Property<string>("Intercom").HasMaxLength(20).HasColumnType("character varying(20)");
                b.Property<string>("Label").HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<double?>("Latitude").HasColumnType("double precision");
                b.Property<double?>("Longitude").HasColumnType("double precision");
                b.Property<string>("Street").IsRequired().HasMaxLength(300).HasColumnType("character varying(300)");
                b.Property<int>("UserId").HasColumnType("integer");
                b.HasKey("Id");
                b.HasIndex("UserId");
                b.ToTable("addresses");
            });

            modelBuilder.Entity("FoodOrder.Domain.Entities.Category", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);
                b.Property<string>("ImageUrl").HasMaxLength(500).HasColumnType("character varying(500)");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<int>("SortOrder").HasColumnType("integer");
                b.HasKey("Id");
                b.HasIndex("SortOrder");
                b.ToTable("categories");
            });

            modelBuilder.Entity("FoodOrder.Domain.Entities.Order", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);
                b.Property<int?>("AddressId").HasColumnType("integer");
                b.Property<string>("Comment").HasMaxLength(500).HasColumnType("character varying(500)");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasDefaultValueSql("now()");
                b.Property<string>("PaymentMethod").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
                b.Property<DateTime?>("RequestedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
                b.Property<decimal>("Total").HasPrecision(10, 2).HasColumnType("numeric(10,2)");
                b.Property<string>("Type").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
                b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone").HasDefaultValueSql("now()");
                b.Property<int>("UserId").HasColumnType("integer");
                b.HasKey("Id");
                b.HasIndex("AddressId");
                b.HasIndex("CreatedAt");
                b.HasIndex("Status");
                b.HasIndex("UserId");
                b.ToTable("orders");
            });

            modelBuilder.Entity("FoodOrder.Domain.Entities.OrderItem", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);
                b.Property<string>("AddonsJson").HasColumnType("jsonb");
                b.Property<string>("ImageUrl").HasMaxLength(500).HasColumnType("character varying(500)");
                b.Property<int>("OrderId").HasColumnType("integer");
                b.Property<int>("ProductId").HasColumnType("integer");
                b.Property<string>("ProductName").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<int>("Quantity").HasColumnType("integer");
                b.Property<string>("RemovedIngredientsJson").HasColumnType("jsonb");
                b.Property<string>("SizeLabel").HasMaxLength(20).HasColumnType("character varying(20)");
                b.Property<decimal>("UnitPrice").HasPrecision(10, 2).HasColumnType("numeric(10,2)");
                b.HasKey("Id");
                b.HasIndex("OrderId");
                b.HasIndex("ProductId");
                b.ToTable("order_items");
            });

            modelBuilder.Entity("FoodOrder.Domain.Entities.OrderReview", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);
                b.Property<string>("Comment").HasMaxLength(1000).HasColumnType("character varying(1000)");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasDefaultValueSql("now()");
                b.Property<int>("OrderId").HasColumnType("integer");
                b.Property<int>("Rating").HasColumnType("integer");
                b.HasKey("Id");
                b.HasIndex("OrderId").IsUnique();
                b.ToTable("order_reviews");
            });

            modelBuilder.Entity("FoodOrder.Domain.Entities.OrderStatusHistory", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);
                b.Property<string>("Note").HasMaxLength(300).HasColumnType("character varying(300)");
                b.Property<DateTime>("OccurredAt").HasColumnType("timestamp with time zone").HasDefaultValueSql("now()");
                b.Property<int>("OrderId").HasColumnType("integer");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
                b.HasKey("Id");
                b.HasIndex("OccurredAt");
                b.HasIndex("OrderId");
                b.ToTable("order_status_history");
            });

            modelBuilder.Entity("FoodOrder.Domain.Entities.OtpCode", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);
                b.Property<string>("Code").IsRequired().HasMaxLength(10).HasColumnType("character varying(10)");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasDefaultValueSql("now()");
                b.Property<DateTime>("ExpiresAt").HasColumnType("timestamp with time zone");
                b.Property<bool>("IsUsed").HasColumnType("boolean");
                b.Property<string>("Phone").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
                b.HasKey("Id");
                b.HasIndex(new[] { "Phone", "IsUsed" });
                b.ToTable("otp_codes");
            });

            modelBuilder.Entity("FoodOrder.Domain.Entities.Product", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);
                b.Property<int>("Calories").HasColumnType("integer");
                b.Property<int>("CategoryId").HasColumnType("integer");
                b.Property<string>("Description").HasMaxLength(1000).HasColumnType("character varying(1000)");
                b.Property<string>("ImageUrl").HasMaxLength(500).HasColumnType("character varying(500)");
                b.Property<bool>("IsAvailable").HasColumnType("boolean").HasDefaultValue(true);
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<decimal>("Price").HasPrecision(10, 2).HasColumnType("numeric(10,2)");
                b.Property<int>("SortOrder").HasColumnType("integer");
                b.Property<string>("Tags").HasMaxLength(500).HasColumnType("character varying(500)");
                b.Property<int>("WeightGrams").HasColumnType("integer");
                b.HasKey("Id");
                b.HasIndex("CategoryId");
                b.HasIndex("IsAvailable");
                b.HasIndex("SortOrder");
                b.ToTable("products");
            });

            modelBuilder.Entity("FoodOrder.Domain.Entities.ProductAddon", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);
                b.Property<string>("ImageUrl").HasMaxLength(500).HasColumnType("character varying(500)");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<decimal>("Price").HasPrecision(10, 2).HasColumnType("numeric(10,2)");
                b.Property<int>("ProductId").HasColumnType("integer");
                b.Property<int>("SortOrder").HasColumnType("integer");
                b.HasKey("Id");
                b.HasIndex("ProductId");
                b.ToTable("product_addons");
            });

            modelBuilder.Entity("FoodOrder.Domain.Entities.ProductIngredient", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<int>("ProductId").HasColumnType("integer");
                b.Property<int>("SortOrder").HasColumnType("integer");
                b.HasKey("Id");
                b.HasIndex("ProductId");
                b.ToTable("product_ingredients");
            });

            modelBuilder.Entity("FoodOrder.Domain.Entities.ProductSize", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);
                b.Property<string>("Label").IsRequired().HasMaxLength(10).HasColumnType("character varying(10)");
                b.Property<decimal>("PriceDelta").HasPrecision(10, 2).HasColumnType("numeric(10,2)");
                b.Property<int>("ProductId").HasColumnType("integer");
                b.Property<int>("SortOrder").HasColumnType("integer");
                b.Property<int?>("WeightGrams").HasColumnType("integer");
                b.HasKey("Id");
                b.HasIndex("ProductId");
                b.ToTable("product_sizes");
            });

            modelBuilder.Entity("FoodOrder.Domain.Entities.User", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasDefaultValueSql("now()");
                b.Property<string>("Email").HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<string>("Name").HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<string>("Phone").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
                b.HasKey("Id");
                b.HasIndex("Phone").IsUnique();
                b.ToTable("users");
            });

            // Relationships
            modelBuilder.Entity("FoodOrder.Domain.Entities.Address", b =>
            {
                b.HasOne("FoodOrder.Domain.Entities.User", "User")
                    .WithMany("Addresses").HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("User");
            });

            modelBuilder.Entity("FoodOrder.Domain.Entities.Order", b =>
            {
                b.HasOne("FoodOrder.Domain.Entities.Address", "Address")
                    .WithMany("Orders").HasForeignKey("AddressId").OnDelete(DeleteBehavior.SetNull);
                b.HasOne("FoodOrder.Domain.Entities.User", "User")
                    .WithMany("Orders").HasForeignKey("UserId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.Navigation("Address");
                b.Navigation("User");
            });

            modelBuilder.Entity("FoodOrder.Domain.Entities.OrderItem", b =>
            {
                b.HasOne("FoodOrder.Domain.Entities.Order", "Order")
                    .WithMany("Items").HasForeignKey("OrderId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("FoodOrder.Domain.Entities.Product", "Product")
                    .WithMany().HasForeignKey("ProductId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.Navigation("Order");
                b.Navigation("Product");
            });

            modelBuilder.Entity("FoodOrder.Domain.Entities.OrderReview", b =>
            {
                b.HasOne("FoodOrder.Domain.Entities.Order", "Order")
                    .WithOne("Review").HasForeignKey("FoodOrder.Domain.Entities.OrderReview", "OrderId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Order");
            });

            modelBuilder.Entity("FoodOrder.Domain.Entities.OrderStatusHistory", b =>
            {
                b.HasOne("FoodOrder.Domain.Entities.Order", "Order")
                    .WithMany("StatusHistory").HasForeignKey("OrderId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Order");
            });

            modelBuilder.Entity("FoodOrder.Domain.Entities.Product", b =>
            {
                b.HasOne("FoodOrder.Domain.Entities.Category", "Category")
                    .WithMany("Products").HasForeignKey("CategoryId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.Navigation("Category");
            });

            modelBuilder.Entity("FoodOrder.Domain.Entities.ProductAddon", b =>
            {
                b.HasOne("FoodOrder.Domain.Entities.Product", "Product")
                    .WithMany("Addons").HasForeignKey("ProductId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Product");
            });

            modelBuilder.Entity("FoodOrder.Domain.Entities.ProductIngredient", b =>
            {
                b.HasOne("FoodOrder.Domain.Entities.Product", "Product")
                    .WithMany("Ingredients").HasForeignKey("ProductId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Product");
            });

            modelBuilder.Entity("FoodOrder.Domain.Entities.ProductSize", b =>
            {
                b.HasOne("FoodOrder.Domain.Entities.Product", "Product")
                    .WithMany("Sizes").HasForeignKey("ProductId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Product");
            });

            modelBuilder.Entity("FoodOrder.Domain.Entities.Address", b =>
            {
                b.Navigation("Orders");
            });
            modelBuilder.Entity("FoodOrder.Domain.Entities.Category", b =>
            {
                b.Navigation("Products");
            });
            modelBuilder.Entity("FoodOrder.Domain.Entities.Order", b =>
            {
                b.Navigation("Items");
                b.Navigation("Review");
                b.Navigation("StatusHistory");
            });
            modelBuilder.Entity("FoodOrder.Domain.Entities.Product", b =>
            {
                b.Navigation("Addons");
                b.Navigation("Ingredients");
                b.Navigation("Sizes");
            });
            modelBuilder.Entity("FoodOrder.Domain.Entities.User", b =>
            {
                b.Navigation("Addresses");
                b.Navigation("Orders");
            });

            modelBuilder.Entity("FoodOrder.Domain.Entities.UserCart", b =>
            {
                b.Property<int>("UserId").HasColumnType("integer");
                b.Property<string>("ItemsJson").IsRequired().HasColumnType("text").HasDefaultValue("[]");
                b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone").HasDefaultValueSql("now()");
                b.HasKey("UserId");
                b.ToTable("user_carts");
                b.HasOne("FoodOrder.Domain.Entities.User", "User")
                    .WithOne().HasForeignKey("FoodOrder.Domain.Entities.UserCart", "UserId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("User");
            });
#pragma warning restore 612, 618
        }
    }
}
